name: mrms-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - python=3.12
  - xarray
  - netcdf4
  - cartopy
  - numpy
  - s3fs
  - fsspec
  - cfgrib
  - matplotlib
  - conda
  - ipykernel
  - conda
  - ipywidgets
  - cftime
  - hvplot
  - metpy
  - siphon
  - cmweather
  - geopandas
  - geoviews
